export const BUSINESS_TYPES = [
  'Agence immobiliere',
  'Architecte',
  'Auto-ecole',
  'Bar',
  'Bijouterie',
  'Boulangerie',
  'Boucherie',
  'Cabinet comptable',
  'Cabinet dentaire',
  'Cabinet medical',
  'Carrosserie',
  'Centre de fitness',
  'Chocolaterie',
  'Coach sportif',
  'Coiffeur',
  'Creperie',
  'Dentiste',
  'Electricien',
  'Estheticienne',
  'Fleuriste',
  'Fromagerie',
  'Garage automobile',
  'Hotel',
  'Institut de beaute',
  'Kinésithérapeute',
  'Librairie',
  'Menuisier',
  'Opticien',
  'Osteopathe',
  'Patisserie',
  'Pharmacie',
  'Photographe',
  'Pizzeria',
  'Plombier',
  'Pressing',
  'Restaurant',
  'Salon de coiffure',
  'Salon de tatouage',
  'Serrurier',
  'Spa',
  'Traiteur',
  'Veterinaire',
]
