// KLUSTER Catalogue des Prestations 2025
// Source: KLUSTER-Catalogue-Prestations-2025.pdf

export type CatalogCategory = {
  id: string
  label: string
  color: string // tailwind color class
  icon: string // lucide icon name
}

export type CatalogItem = {
  id: string
  categoryId: string
  subcategoryId: string
  name: string
  subtitle: string
  description: string
  priceHT: number | null // null = "Sur devis"
  priceLabel: string // display string e.g. "2 390 € HT" or "Sur devis"
  priceUnit?: string // e.g. "/h", "/mois", "/article", "/brief", "/page", "/cocon"
  delay: string
  agencyDiscount: string
  deliverables: string[]
  note?: string
  isPopular?: boolean
}

export type CatalogSubcategory = {
  id: string
  categoryId: string
  label: string
  subtitle: string
}

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  { id: 'dev', label: 'Développement', color: 'bg-blue-500/15 text-blue-400 border-blue-500/20', icon: 'Code2' },
  { id: 'seo', label: 'SEO & Data', color: 'bg-green-500/15 text-green-400 border-green-500/20', icon: 'TrendingUp' },
  { id: 'strategie', label: 'Stratégie', color: 'bg-amber-500/15 text-amber-400 border-amber-500/20', icon: 'Target' },
]

export const CATALOG_SUBCATEGORIES: CatalogSubcategory[] = [
  // Dev
  { id: 'sites-vitrines', categoryId: 'dev', label: 'Sites Vitrines', subtitle: 'Votre présence professionnelle en ligne' },
  { id: 'e-commerce', categoryId: 'dev', label: 'E-Commerce', subtitle: 'Vendez en ligne avec une boutique optimisée' },
  { id: 'autres-dev', categoryId: 'dev', label: 'Autres Développements', subtitle: 'Landing pages, refontes, applications' },
  { id: 'options-dev', categoryId: 'dev', label: 'Options Développement', subtitle: 'Compléments à la carte' },
  { id: 'maintenance', categoryId: 'dev', label: 'Maintenance & Support', subtitle: 'Sérénité au quotidien' },
  // SEO
  { id: 'audits-seo', categoryId: 'seo', label: 'Audits SEO', subtitle: 'Diagnostic complet de votre visibilité' },
  { id: 'accompagnement-seo', categoryId: 'seo', label: 'Accompagnement SEO', subtitle: 'Optimisation continue de votre visibilité' },
  { id: 'strategie-contenu', categoryId: 'seo', label: 'Stratégie de Contenu SEO', subtitle: 'Cocons sémantiques et planning éditorial' },
  { id: 'redaction', categoryId: 'seo', label: 'Rédaction de Contenu', subtitle: 'Articles optimisés SEO' },
  { id: 'consulting-seo', categoryId: 'seo', label: 'Consulting & Formation SEO', subtitle: 'Expertise à la demande' },
  // Stratégie
  { id: 'audits-strategiques', categoryId: 'strategie', label: 'Audits Stratégiques', subtitle: 'Vision claire de votre situation' },
  { id: 'branding', categoryId: 'strategie', label: 'Positionnement & Branding', subtitle: 'Définir qui vous êtes' },
  { id: 'data-dashboards', categoryId: 'strategie', label: 'Data & Dashboards', subtitle: 'Vos données en décisions' },
  { id: 'options-transversales', categoryId: 'strategie', label: 'Options Transversales', subtitle: 'Services complémentaires' },
]

export const CATALOG_ITEMS: CatalogItem[] = [
  // ===================== SITES VITRINES =====================
  {
    id: 'site-vitrine-headless',
    categoryId: 'dev',
    subcategoryId: 'sites-vitrines',
    name: 'Site Vitrine Headless',
    subtitle: 'Architecture moderne Next.js + WordPress',
    description: 'Site vitrine haute performance avec architecture découplée. Temps de chargement < 1s, sécurité renforcée, SEO optimisé dès la conception.',
    priceHT: 2390,
    priceLabel: '2 390 € HT',
    delay: '2 à 4 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      '5 pages personnalisées',
      '2 gabarits dynamiques réutilisables',
      'Design responsive mobile-first',
      'Formulaire de contact sécurisé',
      'Intégration Google Analytics 4',
      'Formation administration (1h)',
      'Documentation utilisateur',
    ],
    isPopular: true,
  },
  {
    id: 'site-vitrine-theme-premium',
    categoryId: 'dev',
    subcategoryId: 'sites-vitrines',
    name: 'Site Vitrine Thème Premium',
    subtitle: 'WordPress avec thème personnalisé',
    description: 'Site professionnel basé sur un thème premium personnalisé à votre image. Excellent rapport qualité/prix, administration intuitive.',
    priceHT: 1690,
    priceLabel: '1 690 € HT',
    delay: '2 à 3 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      '7 pages personnalisées',
      '2 pages dynamiques (catégories/blog, articles)',
      'Thème premium adapté à votre charte',
      'Design responsive',
      'Formulaire de contact',
      'Formation administration (1h)',
      'Documentation utilisateur',
    ],
    note: '30% plus économique que l\'option Headless',
  },
  {
    id: 'site-vitrine-statique',
    categoryId: 'dev',
    subcategoryId: 'sites-vitrines',
    name: 'Site Vitrine Statique',
    subtitle: 'Performance maximale, budget maîtrisé',
    description: 'Site statique haute performance pour projets nécessitant peu de mises à jour. Hébergement gratuit inclus.',
    priceHT: 1890,
    priceLabel: 'À partir de 1 890 €',
    delay: '1 à 2 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'Jusqu\'à 7 pages sur-mesure',
      '2 pages dynamiques (catégories/blog, articles)',
      'Design responsive',
      'Formulaire de contact',
      'Hébergement Vercel/Netlify',
      'Certificat SSL inclus',
    ],
    note: 'Modifications par développeur uniquement',
  },

  // ===================== E-COMMERCE =====================
  {
    id: 'ecommerce-theme-premium',
    categoryId: 'dev',
    subcategoryId: 'e-commerce',
    name: 'E-commerce Thème Premium',
    subtitle: 'Boutique WooCommerce clé en main',
    description: 'Boutique en ligne professionnelle avec thème premium. Paiement sécurisé, gestion des stocks, emails automatisés.',
    priceHT: 2990,
    priceLabel: '2 990 € HT',
    delay: '3 à 5 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'Boutique complète responsive',
      'Catalogue jusqu\'à 30 produits',
      'Back-office gestion produits',
      'Paiement Stripe et/ou PayPal',
      'Gestion commandes et stocks',
      '5 templates emails transactionnels',
      'Pages légales (CGV, mentions)',
      'Formation administration (2h)',
      'Support post-lancement (1 mois)',
    ],
    note: 'Idéal pour catalogues < 30 produits',
  },
  {
    id: 'ecommerce-sur-mesure',
    categoryId: 'dev',
    subcategoryId: 'e-commerce',
    name: 'E-commerce Sur-Mesure',
    subtitle: 'Design et fonctionnalités personnalisés',
    description: 'Boutique sur-mesure avec design unique et tunnel d\'achat optimisé. Architecture adaptée à vos besoins spécifiques.',
    priceHT: 3990,
    priceLabel: '3 990 € HT',
    delay: '5 à 8 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'Design sur-mesure complet',
      'Catalogue jusqu\'à 30 produits',
      'Tunnel d\'achat personnalisé',
      'Emails transactionnels sur-mesure',
      'Formation administration (2h)',
      'Support post-lancement (1 mois)',
    ],
    note: 'Au-delà de 30 produits : appel découverte requis',
  },
  {
    id: 'ecommerce-30-plus',
    categoryId: 'dev',
    subcategoryId: 'e-commerce',
    name: 'E-commerce +30 produits',
    subtitle: 'Catalogues importants et fonctionnalités avancées',
    description: 'Solution e-commerce pour catalogues conséquents ou besoins spécifiques (multi-vendeurs, ERP, logistique).',
    priceHT: null,
    priceLabel: 'Sur devis',
    delay: 'Variable',
    agencyDiscount: '',
    deliverables: [
      'Appel découverte gratuit (30 min)',
      'Proposition technique détaillée',
      'Devis personnalisé',
    ],
    note: 'Appel découverte obligatoire pour évaluer la complexité',
  },

  // ===================== AUTRES DEV =====================
  {
    id: 'landing-page',
    categoryId: 'dev',
    subcategoryId: 'autres-dev',
    name: 'Landing Page',
    subtitle: 'Une page, un objectif, des conversions',
    description: 'Page d\'atterrissage optimisée pour la conversion. Idéale pour campagnes marketing, lancements produits, capture de leads.',
    priceHT: 690,
    priceLabel: '690 € HT',
    delay: '1 à 2 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'Landing page responsive',
      'Design conversion-first',
      'Formulaire de capture intégré',
      'Tracking GA4 + événements',
      'Version mobile optimisée',
    ],
  },
  {
    id: 'refonte-site',
    categoryId: 'dev',
    subcategoryId: 'autres-dev',
    name: 'Refonte de Site',
    subtitle: 'Moderniser sans perdre votre référencement',
    description: 'Reconstruction complète sur bases modernes avec migration SEO-safe. Préservation et amélioration de votre référencement.',
    priceHT: 2390,
    priceLabel: 'À partir de 2 390 €',
    delay: '4 à 8 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'Audit technique de l\'existant',
      'Plan de migration SEO',
      'Nouveau site complet',
      'Redirections 301 automatiques',
      'Migration du contenu',
      'Comparatif performances avant/après',
      'Formation nouvelle interface',
    ],
  },
  {
    id: 'refonte-theme-premium',
    categoryId: 'dev',
    subcategoryId: 'autres-dev',
    name: 'Refonte vers Thème Premium',
    subtitle: 'Refonte économique',
    description: 'Modernisation vers WordPress + thème premium. Solution économique pour sites vitrines simples.',
    priceHT: 1690,
    priceLabel: 'À partir de 1 690 €',
    delay: '2 à 4 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'Audit léger de l\'existant',
      'Plan de migration SEO',
      'Nouveau site WordPress',
      'Redirections 301',
      'Formation administration (1h)',
    ],
    note: 'Sites vitrines simples uniquement (< 20 pages)',
  },
  {
    id: 'application-web-sur-mesure',
    categoryId: 'dev',
    subcategoryId: 'autres-dev',
    name: 'Application Web Sur-Mesure',
    subtitle: 'Outils métiers et solutions personnalisées',
    description: 'Application web conçue pour vos besoins spécifiques. Dashboard, outil de gestion, portail client, mini-SaaS.',
    priceHT: null,
    priceLabel: 'Sur devis',
    delay: '8 à 16 semaines',
    agencyDiscount: '',
    deliverables: [
      'Appel découverte gratuit (30 min)',
      'Phase de cadrage fonctionnel',
      'Spécifications détaillées',
      'Application fonctionnelle déployée',
      'API REST documentée',
      'Documentation technique',
      'Formation utilisateurs',
    ],
    note: 'Chaque projet étant unique, un appel découverte est obligatoire',
  },

  // ===================== OPTIONS DEV =====================
  {
    id: 'page-supplementaire',
    categoryId: 'dev',
    subcategoryId: 'options-dev',
    name: 'Page supplémentaire',
    subtitle: 'Page statique additionnelle',
    description: 'Page statique additionnelle intégrée à votre site.',
    priceHT: 300,
    priceLabel: '300 € HT',
    delay: '2-3 jours',
    agencyDiscount: '-10%',
    deliverables: ['Page responsive intégrée'],
  },
  {
    id: 'gabarit-dynamique',
    categoryId: 'dev',
    subcategoryId: 'options-dev',
    name: 'Gabarit dynamique',
    subtitle: 'Template réutilisable',
    description: 'Template réutilisable (page service, étude de cas, etc.).',
    priceHT: 350,
    priceLabel: '350 € HT',
    delay: '3-5 jours',
    agencyDiscount: '-10%',
    deliverables: ['Gabarit fonctionnel'],
  },
  {
    id: 'formulaire-avance',
    categoryId: 'dev',
    subcategoryId: 'options-dev',
    name: 'Formulaire avancé',
    subtitle: 'Multi-étapes, conditionnel, CRM',
    description: 'Formulaire multi-étapes, conditionnel, avec intégration CRM.',
    priceHT: 490,
    priceLabel: '490 € HT',
    delay: '3-5 jours',
    agencyDiscount: '-10%',
    deliverables: ['Formulaire fonctionnel', 'Intégration configurée'],
  },
  {
    id: 'integration-api-tierce',
    categoryId: 'dev',
    subcategoryId: 'options-dev',
    name: 'Intégration API tierce',
    subtitle: 'Connexion à une API externe',
    description: 'Connexion à une API externe (CRM, ERP, paiement custom).',
    priceHT: 590,
    priceLabel: 'À partir de 590 €',
    delay: 'Variable',
    agencyDiscount: '-10%',
    deliverables: ['Intégration fonctionnelle', 'Documentation'],
    note: 'Tarif selon complexité de l\'API',
  },
  {
    id: 'langue-supplementaire',
    categoryId: 'dev',
    subcategoryId: 'options-dev',
    name: 'Langue supplémentaire',
    subtitle: 'Ajout d\'une langue au site',
    description: 'Ajout d\'une langue au site (hors traduction du contenu).',
    priceHT: 200,
    priceLabel: '200 €/page',
    priceUnit: '/page',
    delay: 'Variable',
    agencyDiscount: '-10%',
    deliverables: ['Structure multilingue', 'Sélecteur de langue'],
  },
  {
    id: 'animations-premium',
    categoryId: 'dev',
    subcategoryId: 'options-dev',
    name: 'Animations premium',
    subtitle: 'Scroll, parallax, micro-interactions',
    description: 'Animations avancées : scroll, parallax, micro-interactions.',
    priceHT: 590,
    priceLabel: '590 € HT',
    delay: '3-5 jours',
    agencyDiscount: '-10%',
    deliverables: ['Animations intégrées'],
  },

  // ===================== MAINTENANCE =====================
  {
    id: 'maintenance-essentielle',
    categoryId: 'dev',
    subcategoryId: 'maintenance',
    name: 'Maintenance Essentielle',
    subtitle: '129 €/mois - Engagement 12 mois',
    description: 'Maintenance mensuelle : mises à jour, sauvegardes hebdomadaires, monitoring uptime.',
    priceHT: 129,
    priceLabel: '129 €/mois',
    priceUnit: '/mois',
    delay: 'Continu',
    agencyDiscount: '-20%',
    deliverables: [
      'Mises à jour WordPress/plugins',
      'Sauvegarde hebdomadaire',
      'Monitoring uptime',
      '1 intervention mineure/mois',
    ],
  },
  {
    id: 'maintenance-avancee',
    categoryId: 'dev',
    subcategoryId: 'maintenance',
    name: 'Maintenance Avancée',
    subtitle: '290 €/mois - Engagement 12 mois',
    description: 'Maintenance complète avec support prioritaire et heures de modifications incluses.',
    priceHT: 290,
    priceLabel: '290 €/mois',
    priceUnit: '/mois',
    delay: 'Continu',
    agencyDiscount: '-15%',
    deliverables: [
      'Tout le pack Essentiel +',
      'Sauvegarde quotidienne',
      'Support prioritaire',
      '2h de modifications/mois',
      'Rapport mensuel',
      'Optimisation performance',
    ],
    isPopular: true,
  },
  {
    id: 'intervention-ponctuelle',
    categoryId: 'dev',
    subcategoryId: 'maintenance',
    name: 'Intervention ponctuelle',
    subtitle: 'Hors contrat maintenance',
    description: 'Intervention technique hors contrat de maintenance.',
    priceHT: 99,
    priceLabel: '99 €/h',
    priceUnit: '/h',
    delay: 'Sous 48h',
    agencyDiscount: '-10%',
    deliverables: ['Intervention réalisée', 'Compte-rendu'],
    note: 'Minimum 1h facturée',
  },
  {
    id: 'intervention-urgente',
    categoryId: 'dev',
    subcategoryId: 'maintenance',
    name: 'Intervention urgente',
    subtitle: 'Réponse < 4h',
    description: 'Intervention urgente pour situations critiques (site down, hack).',
    priceHT: 175,
    priceLabel: '175 €/h',
    priceUnit: '/h',
    delay: '< 4h',
    agencyDiscount: '',
    deliverables: ['Intervention d\'urgence', 'Rapport d\'incident'],
    note: 'Pour situations critiques uniquement',
  },

  // ===================== AUDITS SEO =====================
  {
    id: 'audit-seo-essentiel',
    categoryId: 'seo',
    subcategoryId: 'audits-seo',
    name: 'Audit SEO Essentiel',
    subtitle: 'Sites < 50 pages',
    description: 'Audit SEO complet en 3 volets : technique, contenu et popularité. Benchmark concurrentiel et plan d\'actions priorisé.',
    priceHT: 460,
    priceLabel: '460 € HT',
    delay: '5 à 7 jours',
    agencyDiscount: '-15%',
    deliverables: [
      'Audit technique (crawl, indexation, vitesse, Core Web Vitals)',
      'Audit contenu (structure Hn, mots-clés, maillage)',
      'Audit popularité (backlinks, autorité)',
      'Benchmark 3 concurrents',
      'Rapport PDF détaillé (30-50 pages)',
      'Plan d\'actions priorisé',
      'Visio de restitution (1h)',
    ],
    note: 'Idéal pour sites vitrines, landing pages, blogs débutants',
  },
  {
    id: 'audit-seo-approfondi',
    categoryId: 'seo',
    subcategoryId: 'audits-seo',
    name: 'Audit SEO Approfondi',
    subtitle: 'Sites 50-100 pages',
    description: 'Audit SEO exhaustif avec analyse des gaps concurrentiels et stratégie de priorisation adaptée à votre secteur.',
    priceHT: 920,
    priceLabel: '920 € HT',
    delay: '7 à 10 jours',
    agencyDiscount: '-15%',
    deliverables: [
      'Audit technique approfondi',
      'Analyse cannibalisation et opportunités sémantiques',
      'Audit backlinks et toxicité',
      'Benchmark 5 concurrents avec gaps',
      'Rapport PDF (50-80 pages)',
      'Plan d\'actions avec estimation d\'impact',
      'Visio de restitution (1h30)',
    ],
    isPopular: true,
  },
  {
    id: 'audit-seo-strategique',
    categoryId: 'seo',
    subcategoryId: 'audits-seo',
    name: 'Audit SEO Stratégique',
    subtitle: 'Sites > 100 pages',
    description: 'Audit exhaustif pour sites complexes avec roadmap stratégique 6-12 mois.',
    priceHT: 1300,
    priceLabel: 'À partir de 1 300 €',
    delay: '10 à 15 jours',
    agencyDiscount: '-10%',
    deliverables: [
      'Audit technique avancé (crawl budget, logs serveur)',
      'Audit contenu à grande échelle (clustering, content pruning)',
      'Stratégie de liens et désaveu si nécessaire',
      'Benchmark 5-10 concurrents',
      'Rapport PDF (80-120 pages)',
      'Roadmap 6-12 mois',
      'Visio de restitution (2h)',
    ],
    note: 'E-commerce, sites médias, marketplaces, sites internationaux',
  },

  // ===================== ACCOMPAGNEMENT SEO =====================
  {
    id: 'accompagnement-heure',
    categoryId: 'seo',
    subcategoryId: 'accompagnement-seo',
    name: 'Accompagnement à l\'heure',
    subtitle: 'Flexibilité maximale',
    description: 'Accompagnement SEO sur-mesure facturé à l\'heure. Optimisations techniques, contenu, suivi des positions.',
    priceHT: 100,
    priceLabel: '100 €/h',
    priceUnit: '/h',
    delay: 'Continu',
    agencyDiscount: '-10%',
    deliverables: [
      'Optimisations techniques',
      'Optimisations de contenu',
      'Suivi des positions',
      'Reporting mensuel',
      'Réunions de suivi',
    ],
    note: 'Minimum 5h. Ordres de grandeur : petit site 5-10h/mois, moyen 10-20h/mois, ambitieux 20-40h/mois',
  },
  {
    id: 'pack-decouverte-seo',
    categoryId: 'seo',
    subcategoryId: 'accompagnement-seo',
    name: 'Pack Découverte',
    subtitle: '5 heures d\'accompagnement',
    description: 'Pack idéal pour un suivi léger ou des actions ciblées sur un petit site.',
    priceHT: 490,
    priceLabel: '490 € HT',
    delay: '1 mois',
    agencyDiscount: '-10%',
    deliverables: [
      '5 heures de travail SEO',
      'Optimisations techniques et contenu',
      '1 rapport de suivi',
      '1 point téléphonique',
    ],
  },
  {
    id: 'pack-croissance-seo',
    categoryId: 'seo',
    subcategoryId: 'accompagnement-seo',
    name: 'Pack Croissance',
    subtitle: '10 heures d\'accompagnement',
    description: 'Format standard pour site vitrine ou PME avec objectifs de croissance modérés.',
    priceHT: 950,
    priceLabel: '950 € HT',
    delay: '1 mois',
    agencyDiscount: '-10%',
    deliverables: [
      '10 heures de travail SEO',
      'Optimisations techniques et contenu',
      'Suivi des positions',
      'Rapport mensuel détaillé',
      'Réunion de suivi (1h)',
    ],
    isPopular: true,
  },
  {
    id: 'pack-performance-seo',
    categoryId: 'seo',
    subcategoryId: 'accompagnement-seo',
    name: 'Pack Performance',
    subtitle: '20 heures d\'accompagnement',
    description: 'Pour sites ambitieux, e-commerce ou projets avec objectifs de croissance importants.',
    priceHT: 1890,
    priceLabel: '1 890 € HT',
    delay: '1 mois',
    agencyDiscount: '-10%',
    deliverables: [
      '20 heures de travail SEO',
      'Optimisations techniques approfondies',
      'Optimisations contenu avancées',
      'Suivi 50+ mots-clés',
      'Rapport mensuel + dashboard',
      '2 réunions de suivi',
      'Recommandations stratégiques',
    ],
  },

  // ===================== STRATEGIE CONTENU SEO =====================
  {
    id: 'pack-fondation',
    categoryId: 'seo',
    subcategoryId: 'strategie-contenu',
    name: 'Pack Fondation',
    subtitle: '1 cocon · 16 sujets · Audit + Amorce contenu',
    description: 'Pack découverte pour valider l\'approche SEO sur votre marché. 1 cocon sémantique complet avec briefs détaillés + production de contenu starter en IA Premium.',
    priceHT: 590,
    priceLabel: '590 € HT',
    delay: '1 à 2 semaines',
    agencyDiscount: '-15%',
    deliverables: [
      'OFFERT : Audit SEO Essentiel (valeur 460€)',
      '1 cocon sémantique structuré (16 sujets)',
      'Recherche de mots-clés approfondie',
      '16 briefs de rédaction détaillés',
      'Stratégie de maillage interne',
      '3h d\'échanges (cadrage + restitution)',
      'AMORCE CONTENU : 6 articles IA Premium',
    ],
    note: 'Idéal pour tester avant engagement plus important',
  },
  {
    id: 'pack-expansion',
    categoryId: 'seo',
    subcategoryId: 'strategie-contenu',
    name: 'Pack Expansion',
    subtitle: '3 cocons · 48 sujets · Audit + Amorce contenu',
    description: 'Pack pour poser les bases d\'une présence SEO solide. Couvre généralement 3 services ou thématiques clés.',
    priceHT: 1590,
    priceLabel: '1 590 € HT',
    delay: '2 à 3 semaines',
    agencyDiscount: '-15%',
    deliverables: [
      'OFFERT : Audit SEO Essentiel (valeur 460€)',
      '3 cocons sémantiques (48 sujets)',
      'Recherche de mots-clés exhaustive',
      '48 briefs de rédaction détaillés',
      'Stratégie de maillage inter-cocons',
      '5h d\'échanges',
      'AMORCE CONTENU : 18 articles IA Premium',
    ],
    isPopular: true,
  },
  {
    id: 'pack-acceleration',
    categoryId: 'seo',
    subcategoryId: 'strategie-contenu',
    name: 'Pack Accélération',
    subtitle: '5 cocons · 80 sujets · Audit + Formation + Amorce contenu',
    description: 'Pack croissance pour une couverture SEO ambitieuse avec formation de votre équipe.',
    priceHT: 2990,
    priceLabel: '2 990 € HT',
    delay: '3 à 5 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'OFFERT : Audit SEO Approfondi (valeur 920€)',
      '5 cocons sémantiques (80 sujets)',
      '80 briefs de rédaction détaillés',
      '1 journée de formation SEO (7h)',
      '7h d\'échanges stratégiques',
      'AMORCE CONTENU : 30 articles IA Premium',
    ],
  },
  {
    id: 'pack-domination',
    categoryId: 'seo',
    subcategoryId: 'strategie-contenu',
    name: 'Pack Domination',
    subtitle: '10 cocons · 160 sujets · Audit + Formation + Suivi 6 mois',
    description: 'Pack complet pour dominer votre marché en SEO. Couverture exhaustive avec suivi sur 6 mois.',
    priceHT: 5490,
    priceLabel: '5 490 € HT',
    delay: '4 à 6 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'OFFERT : Audit SEO Stratégique (valeur 1300€)',
      '10 cocons sémantiques (160 sujets)',
      '160 briefs de rédaction détaillés',
      '1 journée de formation SEO',
      '10h d\'échanges stratégiques',
      '6 mois de reporting mensuel',
      'AMORCE CONTENU : 60 articles IA Premium',
    ],
  },
  {
    id: 'cocon-fondation',
    categoryId: 'seo',
    subcategoryId: 'strategie-contenu',
    name: 'Cocon Fondation',
    subtitle: '1 cocon · 16 sujets · Stratégie seule',
    description: 'Architecture sémantique seule, sans production de contenu.',
    priceHT: 295,
    priceLabel: '295 € HT',
    delay: '1 semaine',
    agencyDiscount: '-15%',
    deliverables: [
      '1 cocon sémantique structuré (16 sujets)',
      'Recherche de mots-clés approfondie',
      '16 briefs de rédaction détaillés',
      'Stratégie de maillage interne',
      '2h d\'échanges (cadrage + restitution)',
    ],
    note: 'Sans production de contenu - briefs uniquement',
  },
  {
    id: 'option-contenu-existant',
    categoryId: 'seo',
    subcategoryId: 'strategie-contenu',
    name: 'Option Contenu Existant',
    subtitle: 'Supplément par cocon',
    description: 'Supplément si votre site dispose déjà de contenu. Analyse de l\'existant, cannibalisations, recommandations.',
    priceHT: 100,
    priceLabel: '+100 €/cocon',
    priceUnit: '/cocon',
    delay: '-',
    agencyDiscount: '',
    deliverables: [
      'Audit du contenu existant',
      'Analyse des cannibalisations',
      'Mapping contenu actuel vs opportunités',
      'Recommandations mise à jour vs création',
    ],
  },

  // ===================== RÉDACTION =====================
  {
    id: 'brief-redaction-seo',
    categoryId: 'seo',
    subcategoryId: 'redaction',
    name: 'Brief de rédaction SEO',
    subtitle: 'Brief complet pour article',
    description: 'Brief complet pour article : analyse SERP, benchmark 10 concurrents, structure recommandée.',
    priceHT: 15,
    priceLabel: '15 €/brief',
    priceUnit: '/brief',
    delay: '1-2 jours',
    agencyDiscount: '',
    deliverables: [
      'Analyse SERP complète',
      'Benchmark contenu des 10 premiers',
      'Structure d\'article recommandée',
      'Mots-clés principaux et secondaires',
      'Intention de recherche identifiée',
    ],
    note: 'Minimum 5 briefs',
  },
  {
    id: 'article-ia-optimise',
    categoryId: 'seo',
    subcategoryId: 'redaction',
    name: 'Article IA Optimisé',
    subtitle: '1000-1200 mots',
    description: 'Article rédigé par IA, optimisé SEO, relu par un humain. Brief requis.',
    priceHT: 20,
    priceLabel: '20 €/article',
    priceUnit: '/article',
    delay: '2-3 jours',
    agencyDiscount: '',
    deliverables: [
      'Article 1000-1200 mots',
      'Structure Hn respectée',
      'Relecture et corrections humaines',
      'Optimisation balises (title, meta)',
      'Suggestions maillage interne',
    ],
    note: 'Minimum 5 articles. Brief requis (option 15€ ou brief client)',
  },
  {
    id: 'article-ia-premium',
    categoryId: 'seo',
    subcategoryId: 'redaction',
    name: 'Article IA Premium',
    subtitle: '1000-1200 mots · Brief personnalisable',
    description: 'Article IA avec brief sur-mesure intégrant vos éléments de marque, ton et optimisation avancée.',
    priceHT: 50,
    priceLabel: '50 €/article',
    priceUnit: '/article',
    delay: '3-4 jours',
    agencyDiscount: '',
    deliverables: [
      'Brief personnalisable inclus',
      'Article 1000-1200 mots',
      'Optimisation SEO avancée (NLP, sémantique)',
      'Relecture approfondie',
      'Mise en forme éditoriale soignée',
    ],
    note: 'Minimum 5 articles',
  },
  {
    id: 'article-redacteur-expert',
    categoryId: 'seo',
    subcategoryId: 'redaction',
    name: 'Article Rédacteur Expert',
    subtitle: '1200-2000 mots · 100% humain',
    description: 'Article rédigé intégralement par un rédacteur professionnel. Idéal pour contenus stratégiques.',
    priceHT: 200,
    priceLabel: '200 €/article',
    priceUnit: '/article',
    delay: '5-7 jours',
    agencyDiscount: '',
    deliverables: [
      'Recherche approfondie du sujet',
      'Article 1200-2000 mots 100% humain',
      'Optimisation SEO intégrée',
      'Style éditorial travaillé',
      '2 révisions incluses',
    ],
    note: 'Via agence partenaire spécialisée',
  },

  // ===================== CONSULTING & FORMATION SEO =====================
  {
    id: 'consulting-seo',
    categoryId: 'seo',
    subcategoryId: 'consulting-seo',
    name: 'Consulting SEO',
    subtitle: 'Expertise à la demande',
    description: 'Sessions de consulting pour répondre à vos questions, valider vos choix techniques, former vos équipes.',
    priceHT: 100,
    priceLabel: '100 €/h',
    priceUnit: '/h',
    delay: 'Sur rendez-vous',
    agencyDiscount: '-10%',
    deliverables: [
      'Temps de préparation inclus',
      'Session (visio ou présentiel)',
      'Compte-rendu écrit',
      'Recommandations actionnables',
    ],
  },
  {
    id: 'pack-consulting-3h',
    categoryId: 'seo',
    subcategoryId: 'consulting-seo',
    name: 'Pack Consulting 3h',
    subtitle: 'Pack économique',
    description: 'Pack de 3h de consulting SEO. Idéal pour diagnostic rapide ou questions ciblées.',
    priceHT: 290,
    priceLabel: '290 € HT',
    delay: 'Sur rendez-vous',
    agencyDiscount: '-10%',
    deliverables: [
      'Préparation',
      '3h de consulting',
      'Compte-rendu détaillé',
      'Recommandations écrites',
    ],
  },
  {
    id: 'formation-seo-journee',
    categoryId: 'seo',
    subcategoryId: 'consulting-seo',
    name: 'Formation SEO Journée',
    subtitle: '7h effectives · Jusqu\'à 5 participants',
    description: 'Formation SEO intensive adaptée à votre secteur. Combine théorie et pratique sur votre site.',
    priceHT: 750,
    priceLabel: '750 € HT',
    delay: 'Sur rendez-vous',
    agencyDiscount: '-10%',
    deliverables: [
      'Préparation personnalisée',
      '7h de formation effective',
      'Support de formation PDF',
      'Exercices pratiques sur votre site',
      'Audit express en live',
      'Session Q&A',
      'Accès replay (si visio)',
    ],
    note: 'Sur site ou visio. Déplacement hors Bordeaux métropole en sus.',
  },

  // ===================== AUDITS STRATEGIQUES =====================
  {
    id: 'audit-marketing-strategique',
    categoryId: 'strategie',
    subcategoryId: 'audits-strategiques',
    name: 'Audit Marketing Stratégique',
    subtitle: 'Positionnement, cibles, canaux',
    description: 'Analyse complète de votre stratégie marketing : positionnement, personas, canaux d\'acquisition, cohérence de marque.',
    priceHT: 1990,
    priceLabel: '1 990 € HT',
    delay: '2 à 3 semaines',
    agencyDiscount: '-15%',
    deliverables: [
      'Analyse du positionnement actuel',
      'Étude des personas et segments cibles',
      'Audit des canaux d\'acquisition',
      'Benchmark 3-5 concurrents directs',
      'Matrice SWOT marketing',
      'Plan d\'actions priorisé',
    ],
  },
  {
    id: 'audit-digital-360',
    categoryId: 'strategie',
    subcategoryId: 'audits-strategiques',
    name: 'Audit Digital 360°',
    subtitle: 'Check-up complet de votre écosystème',
    description: 'Vue d\'ensemble de votre présence digitale : site, SEO macro, tracking, réseaux sociaux, e-réputation.',
    priceHT: 2490,
    priceLabel: '2 490 € HT',
    delay: '2 à 3 semaines',
    agencyDiscount: '-15%',
    deliverables: [
      'Audit site web (UX, performance, mobile)',
      'Analyse SEO macro',
      'Audit tracking et analytics (GA4, tags)',
      'Audit réseaux sociaux',
      'Analyse e-réputation (avis, mentions)',
      'Scorecard digitale avec KPIs',
      'Plan d\'actions priorisé',
    ],
    isPopular: true,
  },

  // ===================== POSITIONNEMENT & BRANDING =====================
  {
    id: 'positionnement-marque',
    categoryId: 'strategie',
    subcategoryId: 'branding',
    name: 'Positionnement de Marque',
    subtitle: 'Plateforme de marque complète',
    description: 'Ateliers de co-construction pour définir vos cibles, proposition de valeur, territoire de marque et messages clés.',
    priceHT: 2490,
    priceLabel: '2 490 € HT',
    delay: '3 à 4 semaines',
    agencyDiscount: '-15%',
    deliverables: [
      '2-3 ateliers de co-construction',
      'Définition des personas prioritaires (3 fiches)',
      'Proposition de valeur formulée',
      'Territoire de marque défini',
      'Messages clés par cible',
      'Ton de voix et guidelines',
      'Document de positionnement finalisé',
    ],
  },
  {
    id: 'brandbook-charte',
    categoryId: 'strategie',
    subcategoryId: 'branding',
    name: 'Brandbook & Charte',
    subtitle: 'Guide ultime de votre identité',
    description: 'Création d\'un brandbook complet : identité visuelle, règles d\'usage, déclinaisons et templates.',
    priceHT: 2490,
    priceLabel: '2 490 € HT',
    delay: '3 à 5 semaines',
    agencyDiscount: '-15%',
    deliverables: [
      'Palette couleurs (primaires/secondaires)',
      'Typographies et règles typographiques',
      'Règles d\'usage du logo',
      'Déclinaisons print et digital',
      'Templates réseaux sociaux (5)',
      'Brandbook PDF finalisé (30-50 pages)',
      'Kit assets (logos, couleurs, typos)',
    ],
    note: 'Requiert logo existant ou création en amont',
  },

  // ===================== DATA & DASHBOARDS =====================
  {
    id: 'dashboard-kpi',
    categoryId: 'strategie',
    subcategoryId: 'data-dashboards',
    name: 'Dashboard KPI',
    subtitle: 'Looker Studio / Power BI / Metabase',
    description: 'Dashboard interactif connecté à vos sources de données. Vos KPIs enfin lisibles et actionnables.',
    priceHT: 1490,
    priceLabel: '1 490 € HT',
    delay: '2 à 3 semaines',
    agencyDiscount: '-15%',
    deliverables: [
      'Cadrage des KPIs et objectifs',
      'Connexion aux sources (1-2 incluses)',
      'Design et création du dashboard',
      'Configuration filtres et segments',
      'Formation à l\'utilisation (1h)',
      '1 itération de modifications',
    ],
    note: 'Source supplémentaire : +250€',
    isPopular: true,
  },
  {
    id: 'rapport-analyse-data',
    categoryId: 'strategie',
    subcategoryId: 'data-dashboards',
    name: 'Rapport d\'Analyse Data',
    subtitle: 'Insights actionnables',
    description: 'Analyse ponctuelle de vos données pour répondre à 1-3 questions business précises.',
    priceHT: 990,
    priceLabel: '990 € HT',
    delay: '1 à 2 semaines',
    agencyDiscount: '-10%',
    deliverables: [
      'Cadrage des questions business',
      'Import et nettoyage des données',
      'Analyse exploratoire',
      'Visualisations haute qualité (5+)',
      'Rapport PDF avec insights',
      'Recommandations actionnables',
    ],
    note: 'Données structurées, max 100K lignes, 1-3 questions',
  },
  {
    id: 'application-reporting-dediee',
    categoryId: 'strategie',
    subcategoryId: 'data-dashboards',
    name: 'Application Reporting Dédiée',
    subtitle: 'Mini-site sur-mesure',
    description: 'Application web dédiée au reporting avec visualisations interactives et données temps réel.',
    priceHT: 4990,
    priceLabel: 'À partir de 4 990 €',
    delay: '3 à 6 semaines',
    agencyDiscount: '',
    deliverables: [
      'Cadrage fonctionnel et technique',
      'Design UI/UX de l\'interface',
      'Développement Next.js + API',
      'Graphiques interactifs',
      'Système d\'authentification',
      'Responsive design',
      'Documentation technique',
    ],
    note: 'Hébergement et maintenance en sus',
  },

  // ===================== OPTIONS TRANSVERSALES =====================
  {
    id: 'setup-hebergement',
    categoryId: 'strategie',
    subcategoryId: 'options-transversales',
    name: 'Setup hébergement complet',
    subtitle: 'Hébergement + domaine + SSL + emails',
    description: 'Configuration hébergement + domaine + SSL + emails (5 boîtes).',
    priceHT: 250,
    priceLabel: '250 € HT',
    delay: '2-3 jours',
    agencyDiscount: '-15%',
    deliverables: [
      'Choix hébergeur adapté',
      'Configuration serveur',
      'Installation SSL',
      'Configuration DNS',
      'Setup emails (5 boîtes)',
    ],
  },
  {
    id: 'setup-tracking-avance',
    categoryId: 'strategie',
    subcategoryId: 'options-transversales',
    name: 'Setup tracking avancé',
    subtitle: 'GA4 + GTM + événements',
    description: 'Configuration GA4 + GTM + événements personnalisés.',
    priceHT: 490,
    priceLabel: '490 € HT',
    delay: '3-5 jours',
    agencyDiscount: '-15%',
    deliverables: [
      'Configuration GA4',
      'Setup Google Tag Manager',
      'Événements de conversion',
      'Configuration e-commerce (si applicable)',
      'Documentation',
    ],
  },
  {
    id: 'migration-contenu',
    categoryId: 'strategie',
    subcategoryId: 'options-transversales',
    name: 'Migration de contenu',
    subtitle: 'Depuis ancien site',
    description: 'Migration de contenu depuis ancien site.',
    priceHT: 350,
    priceLabel: 'À partir de 350 €',
    delay: 'Variable',
    agencyDiscount: '-15%',
    deliverables: ['Contenu migré', 'Vérification intégrité'],
    note: 'Tarif selon volume',
  },
  {
    id: 'formation-personnalisee',
    categoryId: 'strategie',
    subcategoryId: 'options-transversales',
    name: 'Formation personnalisée',
    subtitle: 'WordPress, SEO, analytics...',
    description: 'Formation sur-mesure (WordPress, SEO, analytics...).',
    priceHT: 110,
    priceLabel: '110 €/h',
    priceUnit: '/h',
    delay: 'Sur rendez-vous',
    agencyDiscount: '-10%',
    deliverables: [
      'Support de formation',
      'Exercices pratiques',
      'Accès replay (si visio)',
    ],
    note: 'Sessions de 2h minimum',
  },
  {
    id: 'formation-demi-journee',
    categoryId: 'strategie',
    subcategoryId: 'options-transversales',
    name: 'Formation demi-journée',
    subtitle: '3h30 effectives',
    description: 'Formation demi-journée sur un sujet ciblé.',
    priceHT: 390,
    priceLabel: '390 € HT',
    delay: 'Sur rendez-vous',
    agencyDiscount: '-10%',
    deliverables: [
      'Support de formation',
      'Exercices pratiques',
      'Accès replay',
      'Q&A inclus',
    ],
  },
]

// ===================== PACKS CLÉS EN MAIN =====================
export type CatalogPack = {
  id: string
  name: string
  subtitle: string
  priceHT: number
  priceLabel: string
  savings: string
  delay: string
  includes: string[]
  idealFor: string
  isPopular?: boolean
  isAgency?: boolean
}

export const CATALOG_PACKS: CatalogPack[] = [
  {
    id: 'pack-lancement',
    name: 'Pack Lancement',
    subtitle: 'L\'essentiel pour démarrer',
    priceHT: 2890,
    priceLabel: '2 890 € HT',
    savings: '240 € HT',
    delay: '2 à 4 semaines',
    includes: ['Site Vitrine Headless', 'Setup hébergement complet', 'Setup tracking avancé'],
    idealFor: 'Indépendants, TPE, Créateurs d\'entreprise',
    isPopular: true,
  },
  {
    id: 'pack-croissance',
    name: 'Pack Croissance',
    subtitle: 'Visibilité + Performance',
    priceHT: 5490,
    priceLabel: '5 490 € HT',
    savings: '680 € HT',
    delay: '4 à 6 semaines',
    includes: ['Site Vitrine Headless', 'Audit SEO Essentiel', 'Stratégie Contenu (Pack Expansion)', 'Dashboard KPI', 'Setup hébergement'],
    idealFor: 'PME en développement, Commerces locaux, Services B2B',
  },
  {
    id: 'pack-ecommerce-starter',
    name: 'Pack E-commerce Starter',
    subtitle: 'Vendez en ligne sereinement',
    priceHT: 4490,
    priceLabel: '4 490 € HT',
    savings: '430 € HT',
    delay: '3 à 6 semaines',
    includes: ['E-commerce Thème Premium', 'Setup hébergement complet', 'Setup tracking avancé', 'Maintenance Essentielle (12 mois)'],
    idealFor: 'Commerçants, Artisans, Marques D2C',
  },
  {
    id: 'pack-refonte-seo',
    name: 'Pack Refonte + SEO',
    subtitle: 'Nouveau départ optimisé',
    priceHT: 5490,
    priceLabel: '5 490 € HT',
    savings: '670 € HT',
    delay: '5 à 8 semaines',
    includes: ['Refonte de Site', 'Audit SEO Approfondi', 'Stratégie Contenu (Pack Expansion)', 'Setup tracking avancé'],
    idealFor: 'Sites vieillissants, Refonte avec objectifs SEO',
  },
  {
    id: 'pack-premium',
    name: 'Pack Premium',
    subtitle: 'Solution complète clé en main',
    priceHT: 9990,
    priceLabel: '9 990 € HT',
    savings: '1 770 € HT',
    delay: '4 à 6 semaines',
    includes: ['Site Vitrine Headless', 'Audit SEO Approfondi', 'Stratégie Contenu (Pack Expansion)', 'Accompagnement SEO 6 mois (Pack Performance)', 'Dashboard KPI', 'Setup hébergement', 'Setup tracking avancé'],
    idealFor: 'PME ambitieuses, Projets avec objectifs de croissance',
    isPopular: true,
  },
  {
    id: 'pack-agence-dev',
    name: 'Pack Agence - Dev',
    subtitle: 'Sous-traitance dev qualité',
    priceHT: 1990,
    priceLabel: '1 990 € HT',
    savings: '',
    delay: '',
    includes: ['Site Vitrine Headless (tarif agence)'],
    idealFor: 'Agences web',
    isAgency: true,
  },
  {
    id: 'pack-agence-seo',
    name: 'Pack Agence - SEO',
    subtitle: 'Expertise SEO en marque blanche',
    priceHT: 2740,
    priceLabel: '2 740 € HT',
    savings: '540 € HT',
    delay: '',
    includes: ['Audit SEO Approfondi (tarif agence)', 'Stratégie Contenu Pack Expansion (tarif agence)'],
    idealFor: 'Agences web',
    isAgency: true,
  },
  {
    id: 'pack-agence-full',
    name: 'Pack Agence - Full Service',
    subtitle: 'Partenariat complet',
    priceHT: 6920,
    priceLabel: '6 920 € HT',
    savings: '1 280 € HT',
    delay: '',
    includes: ['Site Vitrine Headless', 'Audit SEO Essentiel', 'Accompagnement SEO 6 mois', 'Dashboard KPI'],
    idealFor: 'Agences web',
    isAgency: true,
  },
]

// Helper: get all items for a category
export function getCatalogItemsByCategory(categoryId: string) {
  return CATALOG_ITEMS.filter((item) => item.categoryId === categoryId)
}

// Helper: get all items for a subcategory
export function getCatalogItemsBySubcategory(subcategoryId: string) {
  return CATALOG_ITEMS.filter((item) => item.subcategoryId === subcategoryId)
}

// Helper: get item by id
export function getCatalogItemById(id: string) {
  return CATALOG_ITEMS.find((item) => item.id === id)
}
